// ===== ข้อมูลหนังทั้งหมด (ใช้ร่วมกันทั้งหน้าแรกและหน้า Movie Detail) =====
const MOVIES = [
  {
    id: "sky-origins",
    title: "TRUST ME",
    genre: ["Fantasy", "Sci-Fi"],
    Image: "trustme.jpg",
    icon: "🚀",
    status: "showing",
    duration: "4 นาที",
    releaseDate: "22 มกราคม 2569",
    cast: ["นางสาวพรรษา โมะศรี", "นางสาวมนัสนันท์ กลางเมือง", "นางสาวรัตนาพร สามแสน", "นางสาวสุภัสสร คงทน", "นางสาวปิยพัชร สีฟ้า"],
    synopsis: "เมื่อสถานีอวกาศนานาชาติสูญเสียการติดต่อกับโลก นักบินอวกาศกลุ่มสุดท้ายต้องไขปริศนาสัญญาณลึกลับที่อาจเปลี่ยนอนาคตของมนุษยชาติไปตลอดกาล ท่ามกลางแรงกดดันของเวลาและออกซิเจนที่กำลังจะหมดลง",
    videoUrl: "https://drive.google.com/file/d/1KW-KTrDIdABHd2RiHMWtiVCzeJIgfa0l/view?usp=sharing",
  },
  {
    id: "friends-that-day",
    title: "มิตรภาพ ลาบหมู",
    genre: ["Drama", "Comedy"],
    Image: "2.jpg",
    icon: "🎭",
    status: "showing",
    duration: "5 นาที",
    releaseDate: "3 ธันวาคม 2567",
    cast: ["นางสาวธัญยพร คงทน", "นางสาวดวงฤทัย คงทน", "นางสาวสุภัสสร คงทน", "นายอธิวัฒน์ โคตรพัน", "นางสาววันดี สมภาร", "นายกรกิตติ์ สายทอง", "นางสาวพัชรภรณ์ บุญเนตร", "นางสาวรัตนาพร"],
    synopsis: "ภาพยนตร์เล่าถึง หญิง หญิงสาวชาวกรุงเทพฯ ที่เดินทางกลับบ้านยายในชนบทใน ช่วงปิดเทอมพักใจจากชีวิตที่วุ่นวายในเมืองใหญ่ แล้วเธอได้พบกับ อิงและแอน เพื่อนในสมัยเด็กบ้านใกล้ที่มีฝมือทำลาบหมูอร่อย และสร้างมิตรภาพผ่านการเรียนรู้วิธีทำลาบหมูแบบดั้งเดิม",
    trailerId: "2",
    videoUrl:"https://drive.google.com/file/d/1vx2NPFqZsutWJX7cAnSIoACEmgF4qUK8/view?usp=sharing",
  },
  {
    id: "shadow-night",
    title: "ผู้โชคดี",
    genre: ["Thriller", "Drama"],
    Image: "3.jpg",
    icon: "👻",
    status: "showing",
    duration: "5 นาที",
    releaseDate: "7 กุุมภาพันธ์ 2567",
    cast: ["นางสาวสุภัสสร คงทน", "นางสาวธัญยพร คงทน", "นางสาวดวงฤทัย คงทน", "นางสาวเกวลิน ไตรงาม", "นายกรกิตติ์ สายทอง"],
    synopsis: "ขวัญเติบโตมากับพี่สาวเพียงสองคนหลังจากสูญเสียพ่อแม่ ชีวิตของพวกเธอลำบากแต่ก็พยายามดิ้นรนกันไป วันหนึ่งขวัญได้รับอีเมลปริศนาแจ้งว่าเธอได้รับเงินรางวัล 100,000 บาท ด้วยความกดดันจากปัญหาการเงินและความเครียดที่มี เธอหลงเชื่อและกรอกข้อมูลส่วนตัวไป หลังจากนั้นไม่นาน ชายปริศนาโทรมาข่มขู่และใช้ข้อมูลของเธอไปทำธุรกรรมผิดกฎหมาย ทำให้ขวัญเป็นหนี้มหาศาล ความสิ้นหวังและความกดดันทำให้เธอหาทางออกไม่ได้ จนสุดท้ายตัดสินใจจบชีวิตตัวเองลงข่าวการจากไปของเธอสร้างความสะเทือนใจและสะท้อนถึงอันตรายของอาชญากรรมไซเบอร์ที่ส่งผลกระทบต่อชีวิตผู้คน แต่สิ่งที่พวกเขาพบกลับเป็นมากกว่าความทรงจำในอดีต",
    trailerId: "3",
    videoUrl:"https://drive.google.com/file/d/1NfowLyA19ugpFO-I62zXdMju5fcrHZ3j/view?usp=drive_link"
  },
  {
    id: "blue-horizon",
    title: "มนุษย์ UPDATE",
    genre: ["Sci-Fi", "Fantasy"],
    Image: "4.jpg",
    icon: "💙",
    status: "showing",
    duration: "5 นาที",
    releaseDate: "6 กุมพาภันธ์ 2569",
    cast: ["นางสาวพรรษา โมะศรี", "นางสาวธัญยพร คงทน", "นางสาวรัตนาพร สามแสน", "นางสาวสุภัสสร คงทน", "นางสาวปิยพัชร สีฟ้า"],
    synopsis: "โรงเรียนแห่งหนึ่งนำ AI เข้ามาควบคุมและจัดการทุกอย่างเพื่อความสะดวก นักเรียนส่วนใหญ่พึ่งพาและเชื่อระบบโดยไม่ตั้งคำถาม แต่ฟ้าเริ่มสังเกตความผิดปกติ ทั้งข่าวปลอม การปลอมเสียงและใบหน้า รวมถึงผลกระทบที่มองไม่เห็นจากการใช้ทรัพยากรเพื่อเลี้ยงระบบ AI เมื่อทุกคนตอบคำถามเหมือนกัน ฟ้าจึงตั้งคำถามสำคัญว่า หากมนุษย์เชื่อ AI ทุกอย่างโดยไม่คิดเอง เรายังเรียกว่ายัง “คิด” อยู่หรือไม่ เรื่องราวจบลงพร้อมคำถามถึงบทบาทและคุณค่าของมนุษย์ในโลกที่ AI พึ่งพาตัวเองได้",
    trailerId: "4",
    videoUrl:"https://drive.google.com/file/d/1qjoFwxp6EuiKwvUTEUzJ5O3VVPO7rz2Y/view?usp=drive_link"
  },
  {
    id: "agent-seven",
    title: "เชียงใหม่ในอนาคต",
    genre: ["Fantasy"],
    Image: "5.jpg",
    icon: "🕵️",
    status: "showing",
    duration: "7 นาที",
    releaseDate: "6 กันยายน 2568",
    cast: ["นางสาวสุภัสสร คงทน", "นางสาวพรรษา โมะศรี", "นางสาวธัญยพร คงทน", "นางสาวจิรนันท์ แสนสำอาง", "นางสาวมนัสนันท์ กลางเมือง", "นางสาวนาขวัญ สารสิงห์"],
    synopsis: "-",
    trailerId: "5",
    videoUrl: "https://drive.google.com/file/d/1Zoe3WPyMr09MZGWmPJVhlvJgn8vDX_cn/view?usp=sharing"
  },
  {
    id: "heart-never-stops",
    title: "เที่ยวไหนดี",
    genre: ["Adventure"],
    Image: "6.jpg",
    icon: "🏠",
    status: "showing",
    duration: "3 นาที",
    releaseDate: "27 มิถุนายน 2569",
    cast: ["นางสาวธัญยพร คงทน", "นางสาวสุภัสสร คงทน", "นางสาวดวงฤทัย คงทน"],
    synopsis: "-",
    trailerId: "6",
    videoUrl: "https://drive.google.com/file/d/1mq7xNPTo7VsTEkzPFab6sNBL6crcrRuD/view?usp=sharing"
  },
  {
    id: "7",
    title: "Dream or Drug",
    genre: ["Thriller", "Fantasy"],
    Image: "11.jpg",
    icon: "🏠",
    status: "showing",
    duration: "2 นาที",
    releaseDate: "26 กันยายน 2568",
    cast: ["นางสาวสุภัสสร คงทน", "นางสาวธัญยพร คงทน", "นางสาวดวงฤทัย คงทน", "นางสาวจิรนันท์ แสงสำอาง", "นายกรกิตติ์ สายทอง"],
    synopsis: "-",
    trailerId: "6",
    videoUrl:"https://drive.google.com/file/d/1AxatHjw07zXNSZ0z83NlF0qRYJz0pzJ4/view?usp=sharing"
  },
  {
    id: "8",
    title: "โตมากับแลกตาซอย",
    genre: ["Drama"],
    Image: "8.jpg",
    icon: "🏠",
    status: "showing",
    duration: "2 นาที",
    releaseDate: "11 กรกฎาคม 2567",
    cast: ["นางสาวสุภัสสร คงทน", "นางสาวธัญยพร คงทน", "นางสาวดวงฤทัย คงทน", "นางสาวเกวลิน ไตรงาม"],
    synopsis: "-",
    trailerId: "6",
    videoUrl:"https://drive.google.com/file/d/1yl4IIBjX3uc3ik1LLhAo4bkrvENMJ3ff/view?usp=sharing"
  },
  {
  id: "9",   // แก้จาก "heart-never-stops" เป็น "9"
  title: "ทนายอวัยวะ",
  genre: ["Comedy"],
  Image: "9.jpg",
  icon: "🏠",
  status: "showing",
  duration: "3 นาที",
  releaseDate: " มิถุนายน 2569",
  cast: ["นางสาวธัญยพร คงทน", "นางสาวสุภัสสร คงทน", "นางสาวดวงฤทัย คงทน", "นางสาวจิรนันท์ แสงสำอาง", "นางสาวมนัสนันท์ กลางเมือง"],
  synopsis: "-",
  trailerId: "",
  videoUrl: "https://drive.google.com/file/d/1mq7xNPTo7VsTEkzPFab6sNBL6crcrRuD/view?usp=sharing"
},
{
  id: "11",   // แก้จาก "heart-never-stops" เป็น "9"
  title: "เที่ยวอุบลราชธานี",
  genre: ["Adventure"],
  Image: "10.jpg",
  icon: "🏠",
  status: "showing",
  duration: "4 นาที",
  releaseDate: " 1 กันยายน 2567",
  cast: ["นางสาวธัญยพร คงทน", "นางสาวสุภัสสร คงทน"],
  synopsis: "-",
  trailerId: "",
  videoUrl: "https://drive.google.com/file/d/1WGeeKODxJNo4ns2C54dTF00-PVItGfRT/view?usp=drive_link"
},
{
  id: "12",   // แก้จาก "heart-never-stops" เป็น "9"
  title: "วิทยาศาสตร์ Ai",
  genre: ["Comedy"],
  Image: "12.jpg",
  icon: "🏠",
  status: "showing",
  duration: "3 นาที 20 วินาที",
  releaseDate: " มิถุนายน 2569",
  cast: ["นางสาวธัญยพร คงทน", "นางสาวสุภัสสร คงทน", "นางสาวพรรษา โมะศรี", "นางสาวจิรนันท์ แสงสำอาง", "นางสาวมนัสนันท์ กลางเมือง"],
  synopsis: "-",
  trailerId: "",
  videoUrl: "https://drive.google.com/file/d/1L7ILuFQXdPnjYIjGMjp2IGLgESimJVFB/view?usp=sharing"
},
];

function getMovieById(id){
  return MOVIES.find(m => m.id === id);
}